application: remember-fossil
version: dev
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: fossil.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: PIL
  version: latest
